### ISSUE TITLE
Please consider using Hydra

### ISSUE THREAD

**Issue by omry** [timtody/curious#1]
Hi,
I am the author of OmegaConf and Hydra.
Happy to see you are using OmegaConf, please take a look at [Hydra](https://hydra.cc). It's specifically designed with research in mind and I think it can help your project a lot.
Hydra is building on top of OmegaConf, which you are already using so it should be easy to give it a shot.

**Comment by omry** [comment]
Trying it should be easy:
This:
https://github.com/timtody/curious/blob/d0342399e304bd92c62446806f73a615203c6799/reach_constrained.py#L15-L17

Can be replaced with:
```python
@hydra.main(config_path="conf/conf/constrained.yaml")
def main(cfg):
  # the rest of your code.

if __name__ == "__main__":
    main()
```

I suggest you go through the [Hydra tutorial](https://hydra.cc/docs/tutorial/simple_cli), there are a lot of advantages for using Hydra over using OmegaConf directly.

**Comment by timtody** [comment]
Hey Omry, thanks for reaching out. I'm aware the Hydra framework exists and have tried it in the past. Currently, I don't see the benefit in using it over OmegaConf since I don't need any of the extra functionality like sweeps etc. Why exactly would you recommend Hydra over OmegaConf in my case?
Also, love the Dr. Boom :-)

**Comment by omry** [comment]
Hi Julius,
That's a great question, and the answer will be very long, in fact I have a blog post that will be published next week explaining a large part of this which I will not write again now :).

A few things you get now:
- Your project is still not very complex, but those things grow in complexity over time. Hydra makes composition and reuse of configs easy. As you project scales, it will make it easy add and configure different environments, or add support for additional algorithms.
- Tab completion
- Automatic output directory management
- Automatic python logging configuration
- Easy parameter sweeps as you mentioned, eventually you will want to compare things.

And some coming soon:
- Command line driven hyper parameter optimization (once the Ax plugin lands)
- Remote execution once the Ray Launcher plugin lands (send your code directly to AWS, for example).
- It will make it easy to integrate with other frameworks coming that will utilize Hydra (I am expecting some to come out this year, some will be RL frameworks that can help you compare your results to other baselines).

I am also expecting to have plugins to integrate with experimentation tracking frameworks like Weights and biases (you just install the plugin, configure it and it initializes things for you automatically), but that's a bit farther down the road.

Dr.Boom is great, I am a big fan on Hearthstone :)

**Comment by omry** [comment]
In case you missed it, the [blog post](http://bit.ly/2Sdq2B3) is live.
